### ISSUE TITLE
A* algorithm visualisation bug

### ISSUE THREAD

**Issue by darkwarrior730** [finharris/finharris.github.io#7]
It doesn't manage to find the shortest path
![Screenshot from 2021-09-27 15-19-52](https://user-images.githubusercontent.com/27424688/134927823-985ae6bd-346b-4aef-9e01-ef0bee643009.png)

Above is on the default settings (i.e. without inputting anything into the time, start point, or end point boxes)

**Comment by finharris** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/61048847/135050349-9d4e646d-0088-41f3-887d-783432efc1ca.png)
FIXED - parent changes even if current g value is lower than the new one
